In [1]:
!pip install numpy

In [2]:
import numpy as np

n1 = np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [3]:
p1 = [1,2,3,4,5]
p1

[1, 2, 3, 4, 5]

In [4]:
type(n1)

numpy.ndarray

In [5]:
type(p1)

list

In [6]:
# ND => N dimesional

In [7]:
py_list = list(range(1_000_000))
np_array = np.array(py_list)

In [8]:
%%timeit
[x+1 for x in py_list]

220 ms ± 9.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%%timeit
np_array + 1

10.5 ms ± 302 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
### Scalar,Vector,Matrix,Tensor
### 1D,     2D,    3D,     ndarrayler

In [39]:
vector_arr = np.array([10,20,30])
vector_arr

array([10, 20, 30])

In [40]:
# Arrayın Boyutunu Öğrenmek
# ndim -> n dimension

In [41]:
vector_arr2 = np.array([50,60,70])
vector_arr2

array([50, 60, 70])

In [42]:
# Arrayler arası işlemler (Vector)
result = vector_arr + vector_arr2
result

array([ 60,  80, 100])

In [43]:
arr3 = np.array(
    [
        [60,70,100],
        [90,100,110]
    ]
)
arr3.ndim , arr3.shape

(2, (2, 3))

# ! (Shape) Şekil arrayler arası işlem için uyuşma sağlamalıdır.!


In [44]:
arr1 = np.array([10,20])
arr2 = np.array([30,40,50])

arr1.shape, arr2.shape, arr1+arr2

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [45]:
arr4 = np.array(
    [
        [60,20,100],
        [90,10,160]
    ]
)
arr4.ndim , arr4.shape

(2, (2, 3))

In [46]:
result = arr3 + arr4
result

array([[120,  90, 200],
       [180, 110, 270]])

In [47]:
result2 = arr3 - arr4
result2

array([[  0,  50,   0],
       [  0,  90, -50]])

In [48]:
arr5 = np.array([
    [30,40],
    [15,20],
    [50,40]
])
arr5.ndim, arr5.shape

(2, (3, 2))

In [49]:
# (2,3) shape ile (3,2) shape matris toplamı ?
# Shapelerin uygun olması lazım
arr4 + arr5 # Hata

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [50]:
# Reshape İşlemi.
# [30,40],
# [15,20],
# [50,40]
arr4 + arr5.reshape(2,3)

array([[ 90,  60, 115],
       [110,  60, 200]])

In [51]:
arr4 * arr5.reshape(2,3)

array([[1800,  800, 1500],
       [1800,  500, 6400]])

In [52]:
# Dot Product -> İç çarpım, nokta çarpım
# İlk matrisin sütun sayısı ikinci matrisin satır sayısı ile aynı olmalı.
arr4.shape, arr5.shape
result = np.dot(arr4,arr5)
result

array([[ 7100,  6800],
       [10850, 10200]])

In [53]:
# İç çarpıma nerede ihtiyaç duyarız -> Benzerlik, Projeksiyon, Lineer Kombinasyon

### Tensor

In [57]:
tensor1 = np.array(
    [
        [ [10,20],[30,40],[50,60] ],
        [ [10,20],[30,40],[50,60] ],
        [ [10,20],[30,40],[50,60] ],
        [ [10,20],[30,40],[50,60] ],
    ]
)
tensor1.ndim, tensor1.shape

(3, (4, 3, 2))

In [58]:
tensor1.size

24

In [59]:
tensor2 = np.random.randint(0,256,(100,100,3))
tensor2

array([[[ 59,  17, 197],
        [114,  48,  15],
        [ 96, 146, 255],
        ...,
        [ 55,   3,  34],
        [ 19,  93, 160],
        [191, 221,  37]],

       [[200,  45,  88],
        [ 90, 236, 189],
        [139, 197,  87],
        ...,
        [238,  46,  68],
        [133,  56,  12],
        [249,  10, 196]],

       [[229, 149,  84],
        [137, 147, 109],
        [193, 188,  76],
        ...,
        [ 20,  22,  32],
        [138, 145,  94],
        [209, 223,  77]],

       ...,

       [[112, 218,  66],
        [ 28, 213, 231],
        [102,  70,   0],
        ...,
        [168, 133, 112],
        [ 45,  40, 187],
        [226,  34, 245]],

       [[215,  43, 176],
        [ 89, 167, 158],
        [182, 118, 225],
        ...,
        [231, 146, 252],
        [204, 179, 230],
        [134, 180, 119]],

       [[ 99, 164, 175],
        [ 64, 248, 192],
        [ 56, 218,   0],
        ...,
        [171, 231, 156],
        [250, 186, 162],
        [142, 242, 205]]

In [62]:
!pip install PIL
from PIL import Image

ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL


ModuleNotFoundError: No module named 'PIL'